#!/bin/bash
set -e

# Pre-installation script for distiller-genesis
# Meta-package - minimal pre-installation tasks

case "$1" in
    install|upgrade)
        # Nothing to do for meta-package
        :
        ;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
